# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_PortSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_PortSelect(object):
    def setupUi(self, Dialog_PortSelect):
        Dialog_PortSelect.setObjectName("Dialog_PortSelect")
        Dialog_PortSelect.resize(258, 138)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_PortSelect)
        self.buttonBox.setGeometry(QtCore.QRect(60, 100, 161, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox_PortSelect = QtWidgets.QComboBox(Dialog_PortSelect)
        self.comboBox_PortSelect.setGeometry(QtCore.QRect(46, 31, 171, 41))
        self.comboBox_PortSelect.setObjectName("comboBox_PortSelect")

        self.retranslateUi(Dialog_PortSelect)
        self.buttonBox.accepted.connect(Dialog_PortSelect.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_PortSelect.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_PortSelect)

    def retranslateUi(self, Dialog_PortSelect):
        _translate = QtCore.QCoreApplication.translate
        Dialog_PortSelect.setWindowTitle(_translate("Dialog_PortSelect", "Dialog"))
